/**
 * Curated recipe definitions for seed. user_id = NULL, source = 'curated'.
 * Structure matches recipes table: ingredients [{ name, amount, unit }], instructions [{ step, instruction }] or string[].
 */
export interface CuratedRecipeRow {
  title: string;
  description: string;
  cuisine_type: string;
  meal_type: string;
  difficulty: string;
  prep_time: number;
  cook_time: number;
  servings: number;
  ingredients: Array<{ name: string; amount: number; unit: string }>;
  instructions: Array<{ step: number; instruction: string }>;
  tags: string[];
}

export const CURATED_RECIPES: CuratedRecipeRow[] = [
  {
    title: 'Classic Spaghetti Aglio e Olio',
    description: 'Simple Italian pasta with garlic, olive oil, and chili flakes.',
    cuisine_type: 'Italian',
    meal_type: 'dinner',
    difficulty: 'easy',
    prep_time: 10,
    cook_time: 15,
    servings: 4,
    ingredients: [
      { name: 'spaghetti', amount: 400, unit: 'g' },
      { name: 'garlic', amount: 6, unit: 'cloves' },
      { name: 'olive oil', amount: 0.5, unit: 'cup' },
      { name: 'red chili flakes', amount: 1, unit: 'tsp' },
      { name: 'parsley', amount: 0.25, unit: 'cup' },
      { name: 'salt', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Cook spaghetti in salted boiling water until al dente. Reserve 1/2 cup pasta water.' },
      { step: 2, instruction: 'Thinly slice garlic. Heat olive oil in a large pan, add garlic and chili flakes; cook until fragrant.' },
      { step: 3, instruction: 'Add drained pasta and a splash of pasta water. Toss with chopped parsley and serve.' },
    ],
    tags: ['pasta', 'quick', 'vegetarian'],
  },
  {
    title: 'Chicken Stir-Fry',
    description: 'Quick chicken and vegetable stir-fry with soy sauce.',
    cuisine_type: 'Asian',
    meal_type: 'dinner',
    difficulty: 'easy',
    prep_time: 15,
    cook_time: 12,
    servings: 4,
    ingredients: [
      { name: 'chicken breast', amount: 500, unit: 'g' },
      { name: 'bell peppers', amount: 2, unit: 'medium' },
      { name: 'broccoli', amount: 2, unit: 'cups' },
      { name: 'soy sauce', amount: 3, unit: 'tbsp' },
      { name: 'garlic', amount: 2, unit: 'cloves' },
      { name: 'ginger', amount: 1, unit: 'tbsp' },
      { name: 'vegetable oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Slice chicken into thin strips. Cut peppers and broccoli into bite-sized pieces.' },
      { step: 2, instruction: 'Heat oil in a wok. Stir-fry chicken until cooked; set aside.' },
      { step: 3, instruction: 'Stir-fry garlic, ginger, then vegetables. Return chicken, add soy sauce, toss and serve.' },
    ],
    tags: ['chicken', 'stir-fry', 'quick'],
  },
  {
    title: 'Scrambled Eggs with Toast',
    description: 'Creamy scrambled eggs served with buttered toast.',
    cuisine_type: 'American',
    meal_type: 'breakfast',
    difficulty: 'easy',
    prep_time: 2,
    cook_time: 5,
    servings: 2,
    ingredients: [
      { name: 'eggs', amount: 4, unit: 'large' },
      { name: 'butter', amount: 1, unit: 'tbsp' },
      { name: 'milk', amount: 1, unit: 'tbsp' },
      { name: 'bread', amount: 2, unit: 'slices' },
      { name: 'salt', amount: 0.25, unit: 'tsp' },
      { name: 'black pepper', amount: 1, unit: 'pinch' },
    ],
    instructions: [
      { step: 1, instruction: 'Whisk eggs with milk, salt, and pepper.' },
      { step: 2, instruction: 'Melt butter in a non-stick pan over low heat. Pour in eggs and stir gently until set.' },
      { step: 3, instruction: 'Toast bread and serve with scrambled eggs.' },
    ],
    tags: ['breakfast', 'eggs', 'quick'],
  },
  {
    title: 'Tomato Basil Soup',
    description: 'Creamy tomato soup with fresh basil.',
    cuisine_type: 'Italian',
    meal_type: 'lunch',
    difficulty: 'easy',
    prep_time: 10,
    cook_time: 25,
    servings: 4,
    ingredients: [
      { name: 'canned tomatoes', amount: 800, unit: 'g' },
      { name: 'onion', amount: 1, unit: 'medium' },
      { name: 'garlic', amount: 2, unit: 'cloves' },
      { name: 'fresh basil', amount: 0.5, unit: 'cup' },
      { name: 'vegetable broth', amount: 2, unit: 'cups' },
      { name: 'heavy cream', amount: 0.25, unit: 'cup' },
      { name: 'olive oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Sauté chopped onion and garlic in olive oil until soft.' },
      { step: 2, instruction: 'Add tomatoes and broth. Simmer 15 minutes. Add basil.' },
      { step: 3, instruction: 'Blend until smooth. Stir in cream, season with salt and pepper. Serve.' },
    ],
    tags: ['soup', 'vegetarian', 'comfort food'],
  },
  {
    title: 'Beef Tacos',
    description: 'Seasoned ground beef tacos with fresh toppings.',
    cuisine_type: 'Mexican',
    meal_type: 'dinner',
    difficulty: 'easy',
    prep_time: 15,
    cook_time: 15,
    servings: 4,
    ingredients: [
      { name: 'ground beef', amount: 500, unit: 'g' },
      { name: 'taco seasoning', amount: 2, unit: 'tbsp' },
      { name: 'taco shells', amount: 8, unit: 'pieces' },
      { name: 'lettuce', amount: 1, unit: 'cup' },
      { name: 'tomatoes', amount: 2, unit: 'medium' },
      { name: 'cheddar cheese', amount: 1, unit: 'cup' },
      { name: 'sour cream', amount: 0.5, unit: 'cup' },
    ],
    instructions: [
      { step: 1, instruction: 'Brown ground beef in a skillet. Add taco seasoning and a splash of water; simmer.' },
      { step: 2, instruction: 'Warm taco shells according to package.' },
      { step: 3, instruction: 'Fill shells with beef and top with lettuce, diced tomatoes, cheese, and sour cream.' },
    ],
    tags: ['tacos', 'beef', 'mexican'],
  },
  {
    title: 'Greek Salad',
    description: 'Fresh salad with cucumber, tomato, feta, and olives.',
    cuisine_type: 'Greek',
    meal_type: 'lunch',
    difficulty: 'easy',
    prep_time: 15,
    cook_time: 0,
    servings: 4,
    ingredients: [
      { name: 'cucumber', amount: 1, unit: 'large' },
      { name: 'tomatoes', amount: 3, unit: 'medium' },
      { name: 'red onion', amount: 0.5, unit: 'medium' },
      { name: 'feta cheese', amount: 150, unit: 'g' },
      { name: 'kalamata olives', amount: 0.5, unit: 'cup' },
      { name: 'olive oil', amount: 3, unit: 'tbsp' },
      { name: 'oregano', amount: 0.5, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Chop cucumber, tomatoes, and onion. Place in a large bowl.' },
      { step: 2, instruction: 'Add cubed feta and olives.' },
      { step: 3, instruction: 'Drizzle with olive oil, sprinkle oregano, salt, and pepper. Toss and serve.' },
    ],
    tags: ['salad', 'vegetarian', 'healthy'],
  },
  {
    title: 'Pancakes',
    description: 'Fluffy American-style pancakes for breakfast.',
    cuisine_type: 'American',
    meal_type: 'breakfast',
    difficulty: 'easy',
    prep_time: 10,
    cook_time: 15,
    servings: 4,
    ingredients: [
      { name: 'all-purpose flour', amount: 1.5, unit: 'cups' },
      { name: 'baking powder', amount: 3.5, unit: 'tsp' },
      { name: 'milk', amount: 1.25, unit: 'cups' },
      { name: 'egg', amount: 1, unit: 'large' },
      { name: 'butter', amount: 3, unit: 'tbsp' },
      { name: 'sugar', amount: 1, unit: 'tbsp' },
      { name: 'salt', amount: 0.25, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Mix flour, baking powder, sugar, and salt in a bowl.' },
      { step: 2, instruction: 'Whisk milk, egg, and melted butter. Fold into dry ingredients until just combined.' },
      { step: 3, instruction: 'Heat a griddle; pour 1/4 cup batter per pancake. Flip when bubbles form. Serve with syrup.' },
    ],
    tags: ['breakfast', 'pancakes', 'sweet'],
  },
  {
    title: 'Vegetable Curry',
    description: 'Mild coconut vegetable curry with rice.',
    cuisine_type: 'Indian',
    meal_type: 'dinner',
    difficulty: 'medium',
    prep_time: 20,
    cook_time: 30,
    servings: 4,
    ingredients: [
      { name: 'coconut milk', amount: 400, unit: 'ml' },
      { name: 'curry paste', amount: 2, unit: 'tbsp' },
      { name: 'potatoes', amount: 2, unit: 'medium' },
      { name: 'carrots', amount: 2, unit: 'medium' },
      { name: 'green beans', amount: 1, unit: 'cup' },
      { name: 'onion', amount: 1, unit: 'medium' },
      { name: 'vegetable oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Sauté onion in oil. Add curry paste; cook 1 minute.' },
      { step: 2, instruction: 'Add diced potatoes and carrots. Pour in coconut milk; simmer 15 minutes.' },
      { step: 3, instruction: 'Add green beans; cook 5 more minutes. Season and serve with rice.' },
    ],
    tags: ['curry', 'vegetarian', 'indian'],
  },
  {
    title: 'Grilled Cheese Sandwich',
    description: 'Crispy golden sandwich with melted cheese.',
    cuisine_type: 'American',
    meal_type: 'lunch',
    difficulty: 'easy',
    prep_time: 2,
    cook_time: 5,
    servings: 1,
    ingredients: [
      { name: 'bread', amount: 2, unit: 'slices' },
      { name: 'cheddar cheese', amount: 2, unit: 'slices' },
      { name: 'butter', amount: 1, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Butter one side of each bread slice.' },
      { step: 2, instruction: 'Place cheese between slices, buttered sides out. Grill in a pan over medium heat.' },
      { step: 3, instruction: 'Flip when golden; cook until cheese melts. Serve hot.' },
    ],
    tags: ['sandwich', 'quick', 'vegetarian'],
  },
  {
    title: 'Overnight Oats',
    description: 'No-cook oats soaked overnight with yogurt and fruit.',
    cuisine_type: 'American',
    meal_type: 'breakfast',
    difficulty: 'easy',
    prep_time: 5,
    cook_time: 0,
    servings: 1,
    ingredients: [
      { name: 'rolled oats', amount: 0.5, unit: 'cup' },
      { name: 'milk', amount: 0.5, unit: 'cup' },
      { name: 'yogurt', amount: 0.25, unit: 'cup' },
      { name: 'honey', amount: 1, unit: 'tbsp' },
      { name: 'banana', amount: 0.5, unit: 'medium' },
    ],
    instructions: [
      { step: 1, instruction: 'Mix oats, milk, yogurt, and honey in a jar.' },
      { step: 2, instruction: 'Cover and refrigerate overnight.' },
      { step: 3, instruction: 'Top with sliced banana (or berries) before serving.' },
    ],
    tags: ['breakfast', 'oats', 'no-cook', 'healthy'],
  },
  {
    title: 'Chicken Noodle Soup',
    description: 'Hearty soup with chicken, vegetables, and egg noodles.',
    cuisine_type: 'American',
    meal_type: 'lunch',
    difficulty: 'easy',
    prep_time: 15,
    cook_time: 30,
    servings: 6,
    ingredients: [
      { name: 'chicken breast', amount: 400, unit: 'g' },
      { name: 'egg noodles', amount: 2, unit: 'cups' },
      { name: 'carrots', amount: 2, unit: 'medium' },
      { name: 'celery', amount: 2, unit: 'stalks' },
      { name: 'onion', amount: 1, unit: 'medium' },
      { name: 'chicken broth', amount: 6, unit: 'cups' },
      { name: 'parsley', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Poach chicken in broth until cooked; shred. Set aside.' },
      { step: 2, instruction: 'Sauté diced carrot, celery, and onion. Add broth and bring to a boil.' },
      { step: 3, instruction: 'Add noodles; cook until tender. Return chicken; add parsley. Season and serve.' },
    ],
    tags: ['soup', 'chicken', 'comfort food'],
  },
  {
    title: 'Garlic Butter Shrimp',
    description: 'Quick shrimp in garlic butter and lemon.',
    cuisine_type: 'American',
    meal_type: 'dinner',
    difficulty: 'easy',
    prep_time: 5,
    cook_time: 8,
    servings: 2,
    ingredients: [
      { name: 'shrimp', amount: 400, unit: 'g' },
      { name: 'butter', amount: 3, unit: 'tbsp' },
      { name: 'garlic', amount: 4, unit: 'cloves' },
      { name: 'lemon juice', amount: 2, unit: 'tbsp' },
      { name: 'parsley', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Pat shrimp dry. Melt butter in a skillet; add minced garlic.' },
      { step: 2, instruction: 'Add shrimp; cook 2 minutes per side until pink.' },
      { step: 3, instruction: 'Stir in lemon juice and parsley. Serve with bread or rice.' },
    ],
    tags: ['shrimp', 'seafood', 'quick'],
  },
  {
    title: 'Caesar Salad',
    description: 'Classic Caesar with romaine, parmesan, and creamy dressing.',
    cuisine_type: 'American',
    meal_type: 'lunch',
    difficulty: 'easy',
    prep_time: 15,
    cook_time: 0,
    servings: 4,
    ingredients: [
      { name: 'romaine lettuce', amount: 2, unit: 'heads' },
      { name: 'parmesan cheese', amount: 0.5, unit: 'cup' },
      { name: 'croutons', amount: 1, unit: 'cup' },
      { name: 'mayonnaise', amount: 0.25, unit: 'cup' },
      { name: 'lemon juice', amount: 2, unit: 'tbsp' },
      { name: 'garlic', amount: 1, unit: 'clove' },
      { name: 'anchovy paste', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Chop romaine; place in a large bowl.' },
      { step: 2, instruction: 'Mix mayonnaise, lemon juice, minced garlic, and anchovy paste for dressing.' },
      { step: 3, instruction: 'Toss lettuce with dressing, parmesan, and croutons. Serve immediately.' },
    ],
    tags: ['salad', 'classic'],
  },
  {
    title: 'Mashed Potatoes',
    description: 'Creamy mashed potatoes with butter and milk.',
    cuisine_type: 'American',
    meal_type: 'side',
    difficulty: 'easy',
    prep_time: 10,
    cook_time: 20,
    servings: 4,
    ingredients: [
      { name: 'potatoes', amount: 1, unit: 'kg' },
      { name: 'butter', amount: 4, unit: 'tbsp' },
      { name: 'milk', amount: 0.5, unit: 'cup' },
      { name: 'salt', amount: 0.5, unit: 'tsp' },
      { name: 'black pepper', amount: 0.25, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Peel and quarter potatoes. Boil in salted water until tender; drain.' },
      { step: 2, instruction: 'Mash with butter and warm milk until smooth.' },
      { step: 3, instruction: 'Season with salt and pepper. Serve.' },
    ],
    tags: ['sides', 'vegetarian', 'comfort food'],
  },
  {
    title: 'French Toast',
    description: 'Golden fried bread with cinnamon and maple syrup.',
    cuisine_type: 'American',
    meal_type: 'breakfast',
    difficulty: 'easy',
    prep_time: 5,
    cook_time: 10,
    servings: 2,
    ingredients: [
      { name: 'bread', amount: 4, unit: 'slices' },
      { name: 'eggs', amount: 2, unit: 'large' },
      { name: 'milk', amount: 0.25, unit: 'cup' },
      { name: 'cinnamon', amount: 0.5, unit: 'tsp' },
      { name: 'butter', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Whisk eggs, milk, and cinnamon in a shallow dish.' },
      { step: 2, instruction: 'Dip bread slices in the mixture, coating both sides.' },
      { step: 3, instruction: 'Fry in butter over medium heat until golden. Serve with syrup.' },
    ],
    tags: ['breakfast', 'sweet'],
  },
  {
    title: 'Pasta Carbonara',
    description: 'Roman pasta with eggs, pecorino, guanciale, and black pepper.',
    cuisine_type: 'Italian',
    meal_type: 'dinner',
    difficulty: 'medium',
    prep_time: 10,
    cook_time: 20,
    servings: 4,
    ingredients: [
      { name: 'spaghetti', amount: 400, unit: 'g' },
      { name: 'guanciale or pancetta', amount: 150, unit: 'g' },
      { name: 'egg yolks', amount: 4, unit: 'large' },
      { name: 'whole egg', amount: 1, unit: 'large' },
      { name: 'pecorino Romano', amount: 1, unit: 'cup' },
      { name: 'black pepper', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Cook pasta; reserve 1 cup pasta water. Fry guanciale until crispy.' },
      { step: 2, instruction: 'Whisk egg yolks, whole egg, pecorino, and pepper.' },
      { step: 3, instruction: 'Off heat, toss hot pasta with guanciale, then mix in egg mixture and a little pasta water. Serve immediately.' },
    ],
    tags: ['pasta', 'italian', 'classic'],
  },
  {
    title: 'Hummus',
    description: 'Creamy chickpea dip with tahini and lemon.',
    cuisine_type: 'Middle Eastern',
    meal_type: 'snack',
    difficulty: 'easy',
    prep_time: 10,
    cook_time: 0,
    servings: 6,
    ingredients: [
      { name: 'chickpeas', amount: 2, unit: 'cans' },
      { name: 'tahini', amount: 0.25, unit: 'cup' },
      { name: 'lemon juice', amount: 3, unit: 'tbsp' },
      { name: 'garlic', amount: 2, unit: 'cloves' },
      { name: 'olive oil', amount: 2, unit: 'tbsp' },
      { name: 'cumin', amount: 0.5, unit: 'tsp' },
      { name: 'salt', amount: 0.5, unit: 'tsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Drain chickpeas; reserve liquid.' },
      { step: 2, instruction: 'Blend chickpeas, tahini, lemon juice, garlic, cumin, salt, and 2 tbsp reserved liquid until smooth.' },
      { step: 3, instruction: 'Drizzle with olive oil. Serve with pita or vegetables.' },
    ],
    tags: ['dip', 'vegetarian', 'healthy'],
  },
  {
    title: 'Beef Chili',
    description: 'Hearty beef chili with beans and spices.',
    cuisine_type: 'American',
    meal_type: 'dinner',
    difficulty: 'easy',
    prep_time: 15,
    cook_time: 45,
    servings: 6,
    ingredients: [
      { name: 'ground beef', amount: 600, unit: 'g' },
      { name: 'kidney beans', amount: 2, unit: 'cans' },
      { name: 'canned tomatoes', amount: 400, unit: 'g' },
      { name: 'onion', amount: 1, unit: 'large' },
      { name: 'chili powder', amount: 2, unit: 'tbsp' },
      { name: 'cumin', amount: 1, unit: 'tsp' },
      { name: 'garlic', amount: 3, unit: 'cloves' },
    ],
    instructions: [
      { step: 1, instruction: 'Brown beef in a large pot; drain excess fat. Add chopped onion and garlic.' },
      { step: 2, instruction: 'Stir in tomatoes, beans, chili powder, cumin, and 1 cup water. Bring to a boil.' },
      { step: 3, instruction: 'Simmer uncovered 30–40 minutes. Season and serve with sour cream and cheese.' },
    ],
    tags: ['chili', 'beef', 'comfort food'],
  },
  {
    title: 'Omelette',
    description: 'Fluffy three-egg omelette with cheese and herbs.',
    cuisine_type: 'French',
    meal_type: 'breakfast',
    difficulty: 'easy',
    prep_time: 3,
    cook_time: 5,
    servings: 1,
    ingredients: [
      { name: 'eggs', amount: 3, unit: 'large' },
      { name: 'butter', amount: 1, unit: 'tbsp' },
      { name: 'cheddar cheese', amount: 0.25, unit: 'cup' },
      { name: 'chives', amount: 1, unit: 'tbsp' },
      { name: 'salt', amount: 1, unit: 'pinch' },
    ],
    instructions: [
      { step: 1, instruction: 'Beat eggs with salt. Melt butter in a non-stick pan over medium-low.' },
      { step: 2, instruction: 'Pour in eggs. When edges set, lift and tilt to let uncooked egg flow underneath.' },
      { step: 3, instruction: 'Add cheese and chives; fold in half. Slide onto a plate.' },
    ],
    tags: ['breakfast', 'eggs', 'quick'],
  },
  {
    title: 'Minestrone Soup',
    description: 'Italian vegetable and pasta soup.',
    cuisine_type: 'Italian',
    meal_type: 'lunch',
    difficulty: 'easy',
    prep_time: 15,
    cook_time: 35,
    servings: 6,
    ingredients: [
      { name: 'canned tomatoes', amount: 400, unit: 'g' },
      { name: 'white beans', amount: 1, unit: 'can' },
      { name: 'pasta', amount: 1, unit: 'cup' },
      { name: 'zucchini', amount: 1, unit: 'medium' },
      { name: 'carrots', amount: 2, unit: 'medium' },
      { name: 'celery', amount: 2, unit: 'stalks' },
      { name: 'vegetable broth', amount: 4, unit: 'cups' },
      { name: 'basil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      { step: 1, instruction: 'Sauté diced carrot, celery, and zucchini in a pot.' },
      { step: 2, instruction: 'Add tomatoes, broth, and beans. Simmer 20 minutes.' },
      { step: 3, instruction: 'Add pasta; cook until tender. Stir in basil. Season and serve.' },
    ],
    tags: ['soup', 'vegetarian', 'italian'],
  },
];
